name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          # Enable caching of the uv cache
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.14


      - name: Install dependencies
        run: |
          if [ -f pyproject.toml ]; then
            uv sync --all-extras --dev
          elif [ -f requirements.txt ]; then
            uv pip install -r requirements.txt
          fi

      - name: Run tests with pytest
        run: |
          uv run pytest --cov=./ --cov-report=xml:coverage.xml --cov-report=term-missing

      - name: Pytest coverage comment
        if: github.event_name == 'pull_request'
        uses: MishaKav/pytest-coverage-comment@v1.7.2
        with:
          pytest-xml-coverage-path: ./coverage.xml
          junitxml-path: ./pytest.xml
