proxmox:
    api_url: ENC[AES256_GCM,data:53IsPW8QLKjMCA/aJfHdHH+qWldYLKg20RszfzqvWcUsHLoS6w==,iv:BUCuj9wYNCw8BMqHHVV85QEmbP7p4nyrk2b8XDD9leQ=,tag:Wg7Uxiy4BVK9i8goxtYeOg==,type:str]
    api_token_id: ENC[AES256_GCM,data:ty/bqA6iHsUbCfC9SHnpMd//UmsRn/E=,iv:z0H4FxSjLUcCuuyV0MirckXS33jMtfXHs2+OZwlTgsM=,tag:1JpXMM8ruKZ9dfiDNyQG9g==,type:str]
    api_token_secret: ENC[AES256_GCM,data:4z110tbjfLrgqLIuiUb+aTRA2VHyBQr4dl3jvmHnAkLvXokc,iv:WPH5YonwW7OnA7rM4gLaz6gCb8nNk9b+BsIcUKclQuo=,tag:y7fHV8dgb+sFPMzYsocDMQ==,type:str]
    node_name: ENC[AES256_GCM,data:rN3E62D0QCs=,iv:G5WwF6sKUV/Hr8rD0R+gaTLviVlcwI0GwHzCUMFc9BM=,tag:xJDN5hat/onlpYS2zZ+N4g==,type:str]
network_config:
    vlan-10:
        subnet: ENC[AES256_GCM,data:/KXiqI6ibqsD0cZdW6dl,iv:hXFi+dEFz8L/LliHelmSyfyXG7UOYFkL5vdJ8aF85OU=,tag:xYMEGYyNZ0zQwu7ML1rilg==,type:str]
        gateway: ENC[AES256_GCM,data:jMgTKGeAE1aZ6JDP,iv:Zo91lHpapeSvc+nb15H+/vlKJ6E5WwaysqBaDRgHibE=,tag:Z77k0BmmpviUmHtNf5naxw==,type:str]
        nameservers:
            - ENC[AES256_GCM,data:fnwcswpYV342nVLbhNY=,iv:o3sOMgdiGxhlmPDyMeFBf2LcsNba50Ln1mArDd3eIJQ=,tag:ZroXHmKPeaH2odtGrNEmdA==,type:str]
            - ENC[AES256_GCM,data:FvKwTAH+OZhtawVN,iv:kHpVei89+Jd5TxY7JdvgbKm95pUz+kjn+34O3ZyFyKs=,tag:T7zVVFVp6TTuJD9HufZZFw==,type:str]
        public-nameservers-only:
            - ENC[AES256_GCM,data:uyE0PbcOig==,iv:5psPwX5IHhkmxUb94wykXMqe0h3ziobZcjxFkTRtASs=,tag:rHahPDr68OpNJu9ZzEJC0A==,type:str]
            - ENC[AES256_GCM,data:qcW9aW++qQ==,iv:+YhM1EDmsYlGnfqk9M2r5zJjfwH1ZsgjLy2JfqeMvnQ=,tag:eKftgkyc86wT/oC2RP2CqA==,type:str]
    vlan-20:
        subnet: ENC[AES256_GCM,data:Jxo3FH6UjVFHA9TlGuPL,iv:sin/x0/hdeGtFF5SebD1nAWevCxQuAhL0K/1n6D5FY4=,tag:dEmZYdVRUwLj2wPictMZ/Q==,type:str]
        gateway: ENC[AES256_GCM,data:rxUq2+0fXcKiUtJJ,iv:c+X7qir/Omu5c4inEol9cfH2sS8DjgS8mFpCjWjZ360=,tag:QGe0RHxeIgs0miu2+JDJYg==,type:str]
        nameservers:
            - ENC[AES256_GCM,data:iXq2XmkEo8TVc6i0eGU=,iv:wwG8L1WYRMK3RN/EJUxDh+n7ZSqtNwbDdiYm5J5KBT8=,tag:co8zphf0czBgB6wFaW9cpg==,type:str]
            - ENC[AES256_GCM,data:wHPYhutConX8/KeR,iv:FALaYeQLmDCxA9cWu+vFrc6sl97dwMBeQT/4MugRvdg=,tag:lPb6Sp6ul6mPWTOdT9pTqA==,type:str]
        public-nameservers-only:
            - ENC[AES256_GCM,data:r3ipmp7DSA==,iv:G0JyZ2cByMkm8QKMxuiYK6tjMRY8A5jxGYuj8D/dMSY=,tag:TEuwvf2q8MXmN+mOOEv2iQ==,type:str]
            - ENC[AES256_GCM,data:YMHD/DXjWA==,iv:mG4nFT1OCWiDaSrCiHOoKPpsMNCHYqxAgfYuDLJqtBw=,tag:3U8GZa7nVE/Uaefv0aRnsw==,type:str]
    garage_lxc:
        ip: ENC[AES256_GCM,data:ky0JijgCOTxM5/wQVGHUb/U=,iv:/B39qW4iCQT4GLZNTA5tNG2rDT57ruYwATqEhmpK/fw=,tag:3sCP7x+abQ1Yc/tTPbZzxA==,type:str]
        gw: ENC[AES256_GCM,data:NfQM6PEtQp07xN87,iv:uq9YAeXKLtJqGIuKKYdzF4GoenTnnAluT25nWBQp+tA=,tag:WuYPxGwy5JSxzLFrGhZKIw==,type:str]
ssh_keys:
    lxc_admin: ENC[AES256_GCM,data:JlaaK8ZGJ8t4o8vpbk5gs0WLIm8vhl3kuppnVw9OE6Yh64Rp7CfRhWGWR+7Kx78QJkWmrBWPh19RzrnYYFUJCRqSWf1EDQoN+0mfMVy7ap2KfpZ+axDfG46d8qg5LuCt57M=,iv:VnazP+oLDWkmsi+bM9Fek/JZdiKC9k+G/FIzbPdgDTs=,tag:t3ikWHz8MbJBa+gieK+bbg==,type:str]
garage:
    admin_token: ENC[AES256_GCM,data:3iZyhWq6SuVLj0zxzvo1CY925kmn6/lh1cKH56SPzLc31lIY38TDMlyj8IEF4EHI8Ln96q4LwADGRR0z5dtBzw==,iv:ymnq0eiytklAYFNCGK4bYnxANZCXk1VkGzPmgs1dNzY=,tag:eFjCsL9pA9Fjx0OSiZhC7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEM4dk9Xc1lE
            M0NnVXVKbmk4YXlzOFRoak95UFVIbDYwb05vajVxRW9mSGpTTXhRSklVbGZDWXRD
            NG5DdUZvUHRSQk0wY2lKS0o1cTFNZXF4STFHekFqdDl0SDNrWk1Tb1BzRnBaNEQ4
            M3Q2WFZqZCtDakNHdWJ1VENvY21GdTg2bmRpaC9YamE1TTIyZmMwcnAxOXZBSm1C
            WnJMaTJjWXBtZlhhK2JzZXhVb3ZCQzlOdjNmWmFqNDY1WjV6ejU5UG5GMXNMSUY3
            bkljZVVJUUt2RDdrcVpMOGVxWks5c3F5ckF1VlRvREs0WkVxRFVvZjNPUTg3bll0
            bzhoclhmVnNrWnZ5QUx5YisvcytnbmRLVG1hWmg2U0J0T2grMXg0d0E4aWhDR0Jw
            MUxrdWxlbGpaTzBqemx5dVl3ZWk2VHgwZDJsclBvOEVpbkxyNWNzbmc0TkI4K082
            R0plbFNqU3M1Qlg0UUpiVDhKRUh5MXl5cDl1R2tsQjAxVEJ0UXNpMm1ZNU9mRmZX
            b1lpSUpBWStldDN0UFZPWjBBeTU3LzEwT0syUDR4MjFDS21pRGxZNGlNMExxZ1d3
            WlJ5dFE2Rk5acmptMHBWQ2JoWXV0TVV3MTFvSk9nNlpFZmM2Sy82KzFQaXhLZmRG
            dkdZWGpnd25sYWRhQ2NCTDVoWHlCQTIxdkM1ZnQzU0N5M2FsbkErdGhySHBrMExG
            UHhNT1ZvTnpMVWc1d1FNd3g1Rm1Kby9CbTZFS1QwM2FyTHZXRVZDK2pQZzc4Mk1I
            MkxCQlhXaEhramRzU0crVkJIQ2NpdTBvMjNDbXFlUjE1R200b1JGT0RtQkdIcXZU
            dGt0aVUxYnM3ZDcra0JuVk9DZzA3anBzZDJkNk9sM09UWUI3SHNyZDQzNGRzYitK
            RHJnZWhoVUZvVlppK2tpSG05NndWdnU3TlAyeVU0R2VnRGtFZkZzWFZJYU84NVUz
            K0Y4TnQ5clhSZTlvSGVFYWtwNENYWVZBY1ROQXdMT1pVNHdLQmUwMjZCNlF5UUFl
            b3FadktpZVBudmRsVVRHUlppcHF3YWJsck1uYkZ5a1o3YjM2STFwMlJQRGhuRFNU
            c04rTnI5eDNCWGcxVUVWY3RUT3NhcmNDM0ZkZUkvSWxsblZmdmgwUGw2QTdjdVRH
            WUVrcElvUFJOaG5aQWVlRVNYOFBaTkFOczViMVFxeGF2ZkpKOVRYL3Rkbjd6TGNO
            dWxkWHlDZlRGTW1rdmlXdVRTZ0l1N0NGNmo4K0RTcWhMemlKdUxkUXZMMUtUajVZ
            K25PL3FrSVlEZkxkM2ZrdElGZFVQTnJsd3UwelB2alRXWmdrQnN6RlRoTkkvdElZ
            bTBtZGZLVWsyRllpRjNHWkJsczFieUZKeEFSQXI0c2ErakNnb3B6RDRjOWU4eFRU
            RWMxa09rcUEvcUZGcXBVL1d3Skd4aGpOZEZaeW1aTzVGa3pFWkZwR3NrZkdlaFVU
            SmVDbkpZQXdjWnc3eXVZL2FsTk1mcWlwQm1DNmJrTGR4ZTMrcFlLa3k5bU50WS9P
            TDhDL1JwbXBhZ0tlQURaamdNRjR6OUJ6Zlp4RndhRURwVXZkQ21ZWWJkZTJNZFlO
            Q1lFeU1IVjM1V3IwV3ovSkVWc0dnZzE2S2hSRkU1eTNlcXhBYWtXdjJyRERxUU5I
            djIrZUovUFhwNTJBc3Bab0hCM0tOZXNPb1p2QjAzVzBYNlZrMmoyelJmaVU5UUl3
            NFgycHJHbHlFVWd0Z3RBRDRMSytNSTVJU3Vjcmw5TUtiRXFiMS84NjREZjFKUFdF
            a2hLZXhQRUJSdFFKejhNbXJKQmZXSjYxVVVKTVJYUFhSU2NMTWpkR0hJWE40bExs
            d2l4Y2RGNHJNNVplZ3IzUHgrWWdlVWxkRGNpVlZ6ZjErSndkaDFZc0NjR3ZSRkVO
            Y0svRGN5RDJUaTBtWmhFcHF4K1g5Z1p4REdBM2RSZm1UWlhyb29mVDNtU2FJdwpN
            eUNhWThoK2l5Q1FodDhMc1BTeVN2eFVscjhIS1UrMC9VSE9iWEt4NUdzCi0tLSA3
            S1JOTkRPbkhnSnNKWE84UHk1VDQvV2MxNXh6Rmw3U1R4ZCs3VmRlYWpZCspb8ZNe
            d5dbNPxvK4dTHnSmnyrRyWAVhxOa5wL4jPuEhr8Y+aJECp+kEzKM94FQoYssRjZV
            AK9WIq6MX/XhNIE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1usjm3292p45jwd3277uwdksaacqnqd3e234nyev5f9twm77yr0fz6y5pxcyjfgqnt9aw8qereky8mkev59nanps7727u2djxa5avznjsrwar4qq724vcysf6q9gx5surc66qwdytz9ww4a284eayk2sgx5ka50d3sz357uxfx5x26nu4x5s9nffwuyp6qpet7du6up62wuydgdrd5cjasu2v39rka2uywrat0t7gs9t359j0x9u2ljpunlvggrfcz2y8vu3wkkju7nqyfy5qswukvd8njjsmnwt2qra9qjscwmfh5gf3549h7n5r506pncwt3zkn29wrcp7rdvzyu95uw68yqht9xj4hs9470uqvs3hs4lq6n0rdy5a8teyu369n03hfeas9tnxxzjvzpceec6w95uyr37ktrxrr4wflpgrxw3uj73y4w89pkfnurry0jwj29wnt9tj42lzzskpj2kpy7qfdgu44xkayeajme3n002q2av3zs49fl2rgdalzhtyy2e4jhpvlgw2rnpmuxfl59yvux99987vhaewtus7sgnnw3x396pc0py5vgen3rk7hwefgcrt9qeh5hznrtmcrz83ghehp3yws3z0r4jaj2yesmzjkejxh2qjeu5ngtepv7c6qqc6r8z8zxtenmgv04dmkcxj2n9hm5wep8nxtpyhzk4ttvrcqt6lrz0pwqvuvxeey57p2c44tjweetjvve98ek2x9d992sfth4xmrs9jr9pdmq72u37ew3cmq808v98f8z03tvny25sq2nms49a654gu754tl4sh45hrc5wfxy56m872mfqldr998cd3xrkec0tm6n05pdp60r9qg4d26gefg9e0vy824v0ua8x6cmcnfvpwpz444wzh8tq0dzlz3svx8a5ergt7n9dvr9fnqs4066pjzkt3y6psh5pc8v696wq7h77vmy0jt2mwq2z5rghw2r2fzgsfxq35hgy4svzn4tg0mhqsljxz05z3hh8mcg5wdquf7m2m4dnru82jgy4yq0kazjdnargxey8ylz3tc6dyrs7lyjwkqnpnyexay24w9q7feeq429yt9edqdak4yraen7hhvjntak5d6aw0ycvpgmuexruwhpp8vn0s4ndupdjq0auxrmraxt5xr2elrddzx9ajltz3zcl0eqvjxq3zx2sqt6f3mwsq42k343f42km6c79q46dqtqytgllms0ndyjuc0cxf2x3uxvyqp90t3kkt89dxcgw7de3axne4m28mj22clhd084v7xslypgy39xur295zk0frj0q290gakpt2p6sjfthe3frufw7jsed7zrvfvhlmqrxqxwnr349dlegvfr8qg5j8gs2ah2p4r5j0fr9qflfunf76v068mnpzw2kcnlzx09gaszn8mexzfgypfcqm9pa7rdqvem0c2zwnxwzq7lq225cscyfg8w75rgv8j3pj3zfrusv2wm9nqjp5z2wy0fvc752qhkhzlg0r665hmz03wfzh5ycwyuw7q223hup7v5xqg5v9mjmxx9p54uxdm9s7ukpdpvce4wevynjtu5yry8tj2f4qftwjuy5q5m4n2edgyehlqqgpw404h4fqg3xqu8djfhr3meveuyqt542muu5ra24resh82wxvy2vpa2uu27z5669djurggzyeagkgcy229jf35prex33rjk3nxrnp2lwzl5mrs9ewz58e83yyuk5v4v58q2u4ckhf8985vg6262drzmfvj923kp92mu2a9rhwj9vwwvyy8muaa0g2jx4r8qx5uff0k2kp22erug5tjvuhsckpzr3cafzdhsn56rekku42xvgvhr5pwxqkwkc3nja4hl2gxv475g8vjza2xm0u40l0zhc4l3w0hlkt5s8gcl88fhue6f43j2sezelexzwve75gyp5u7n0n5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGZVRDM3Ymls
            bkVRQ1I0Y20xcWt6SWxTMmcvQ01yelUxdS9qMHE4ZVdsa2VMS2E1OWpzL1NBblBi
            cGpNNmlIQ1ZGcHlXSmswWm9wRncrWmtKRHRSR3NNWnY0RmVoeGFZK3NtNUNadmh4
            ckpoYWdDR2dOSWVkUmlHUkkrQWM5R1RibG9wSXp4MVIwaURqK1hFVk9vSTQ4VWVI
            S01kV0phcWZON2RFRnZKT1kxSEc3cU5BbisvZU14czJ4YXdEbjJpZ05rQ1V5Y0Mx
            Smo2NmRYK2VhUi9hdjlaTWhKaVBEZTVzWktGZkJXTDlJc0syaGxwTDZQN2ZTaS9p
            N3J4R0FpVVVIYyt0K0lCck1yRDE0NkpVV3lSSlA1dUpSV3ZYKzlURXBWamhIdmd2
            RktoSzEya3ovRGxZTkZha1RyTytUeUROcUVsTHMrQzVPbjdFZUtYcDNndWFDZHFj
            S1lnLzhGWlF4OVU0cUZRR2N4azVHRFpMbXllTVcrbnZKRSs2RTV0OGJUUVh6TEMy
            TkRSRWhydGpOT3FxQjFXT1RJakxodWNkbTUrWEdRZ2RQNndmM1lCVjlUKzdObHhp
            c2ttZ2JqR2NVYWU4WnovTkdzYVU2T2x2RFNKOXhKWG5OZ3VMWEF1bERuaml4NTYr
            LzEzSG9MR0NyeWRtVnpiTFNPejMvQ0FzZ1F3elo0K2tycGVCcm4reUZ4SmdPd3gy
            V3pXckpRNWZyUHZRMlptbi9MZnNGbmNtWWphWHA0UTB5ai8xVWN3eTgydE1CV2Jx
            aGpsM0wwL25odjRlSkpONi9VRWZudmtXZksxYXVSdzdaSHR4MXJWRk9PRllET3Jr
            VFJVUSt5TWpOOWpwaS92b2ZleXE1RDlzd1NVY2ZoellzdGIwS3ZILzNXeklhY1NE
            S3V5a09WcXZVYnoza2dtL2x4c21yR2pXK0VRS0lZd2pnaSt4M0xpdTBJN0w3cEF3
            Zk4yazdRZy81dE1oZVVNMm0xR3lzQm0yeFFLenlaazRzVGltUkZvdG5pdzN2ZTJ0
            bW0zQjhXZUFMVWJKK0FSU09ZUmVXc1VpdmhyKzFYNnZEZzA1L0xmU2luVFZjeWVr
            eTl4a0xjUHdwRXNZc1QwT1ZqVGk4dU5vcHlvMWY1Z2NCbUNEZ2ZsWkgwUFNBbjQy
            M28raW5FdktGczVnNnFHNjh3Mkd0bDc0QjJ3NGMvMVJ5aGZuVXA3Mng3cmZ0TnlR
            OFBFQ3Ftb1VDbkZ6ZzFYZjl1S3JEWHFJR1dnbVQvL0NvMHVqbHN6d3l3WjlnYkI5
            MzA4eU8yakpsUEJ6U3ZkSmxsbHM2dElxUURNdW5qSWo1M0RyUE40dHZFZ1hwYTds
            djkyMW5OR1g3dnhuSzNZbEk1T1FOUEEyVFhKSUlnK1F3UmY1VFc0a0E0VVhydVln
            VExmdkFnTkh6L0ZuSVRheTZ6aFJEWXE5RmhobUpoaUMvOWxQTkVkcEoycHZvZHZz
            QWF2UjMrbWs0QnZ3QnluNlAvUHFwUjUyVFEvc1M1bm5NUFFjdHJzamhXbFJUMElF
            YVBReEMwd050Y1NDeEN1b0JKRzd1ZENVeStxSnlNRmd3djRPUWFERzJTUzJEWUg1
            eE5kTDI1MzQ2L0p3QjdkRGxqaEpMU2pjMDFWU0l4OE9iTWxBMldCVHF1Q2UrSktt
            Ui9KYU5TMXNsU013QmxTekh1bll4SmtDdDZ0STY0NUFRWFFTbENZaFByUEVjNDFN
            WEFENnRXSXhzZ0p1ZVlVMW03Z041MXF2TkFJbnRzWkVFTjlpbFVxR25jYmhHbThs
            M0FHTm1ZRGlwNm1UKytlS3FXMGZEV0I0alBqMGRQa2lsVzdSV25IVnFzRFdTSVBk
            eURWUElJWnhrSC96eHh0UWNvM3Z3dXJSVUN0ZldkMVMrbjFWcTBGajd1R1h1Qmo1
            WmdTM3BuUVBLOWNQTUZZanJiWGFRZXpvdTRIQkUvZnVMU0xXRnJwcEpobXVNZwps
            RWU3dWdLYkcxYnJmS0FISDZnemJZUkU1bXpweWtzYjNxYnNaTTJYSytZCi0tLSBD
            NnAwdEtDdlNkY3I3aXV3enZnazdYRy9sM1ZheW83ZW1veGZWNGozRWgwCoYyzw0V
            bIYGxayj4TotZXMwVweFBiVy7fx9qLnsHD06dRm4G75u3BKC/8Zm6+Eh465wCi8E
            UKXcGJXSanHVjWo=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1l0f68fyczayfen9sq4rqlag5rxkfwm55246zkeh5fqf5mdphz4ec8e8ftjrk4fm2usx3lctlaryp7nuer00gg7ezrxcvduje28q5jw0q0r80qs6xd9cqwvc4u5g99xgekzuvy5vry8qqq9x9x67vktr6tkwpglsy76pt53d0skd8vge94cytxzvnc5w795mzq0pqza8yw2xrpw4qxvu3h4g0wfe5w6whqhtgkdn7kv0y29krrjch9w88k66pkp83rsarawegr73sgm78j6wughuzegvp37cdjueushv3q6nfjgj0zpd80ek97059f89x0ny9zvlaqspvlkkft03ktnc5ejr2kxc8v8x9adyk7lyzzfh4c5v2gfkqq97zveewf64cy09p9sdmq7d9uaa4p6w9rn2ezfqpj52mvqq4f3pq33vrsdnft5afkvu28smdqx9scs4kae9ur80shxruvzzvg6prmkgjqgqua56zkf8p0pupegw5sxg6x7gjju5kw5duh3d7dgsdk6adjadhux36z3tk2nwmu50hme9f69f67zcr89h7gj7urfuqd9r9dwn6nxef5vc5japfe3mcyey4e0u4vw9rxgz8qyca8vjr9fdr9n26e7mjt4ujfv7nc0pyxyuh5aymtn662d7cj6a8xmznzvk894m8uuky507ag32dffhfze4evwdcxdxv3698sg26skxf76v9t4s2e255csun3fhtjg394n9twztmkayqhac4yd4cj9gv7fvw23te4qfte8a8g9ttryezn4yr69xp2ypjdw3ajvdkf2rlthqup6c957hn2rsag4uk5tqvdgps0c35l8hrn2z6gmzahy0e0jerq63j7uryh9wus7keywledu5w9pt4wmlheryew2hzl289prz8hmeph6ykeethwewpmvrfkyzxh9wy4hefxyu6vw0gs8zuknyswdpcry8tfh4ldzh0cwhac6qveajk0sspqhn4qxj9c67hzjaffr9cyta25qgqw92hxeq3rktlhnj5zyvtyu8e2qxp245plnzrnva8fjt4w98gkrqpqdfvp4qznqa8lhdxd46q2kdugv5wfds7p5zfaljer2xmgynp0p0el3zpafu69s2xghdtz9gx8pm6dkj8vvtrvm53x6sjqtxf27nalffcu2asve8sxmamc2r93p5qqkfdmznkxgtvyalxxc947az0gufytusna4dx3du3xq86aqpk756tvhneyspnqs6tvh523jslg5a3ffckvkf3ts2fcxzgjusjq4mv4a2zz0cxz37j2smvgs9capa3xm4j8pqnpatcnygjtfjptr9fuc4gdr9cqhsd3vq4apymnfz6enqvkhq3rgt2f2yyw9hrfjeqqmfhuv8tp6d8cgnh78pm947q9jpjagesh986ckm9x94dvq2zua3rjcst8yf992tsqashksmwtdaep0uek36hq8d2h3wyg5a87mfsx4zcxt67sla0jk95l3aut952daf3868tcj9r2f4jxd67x4fsc5t9gsdqe9dkpjctd2vz06fru6u58x9uvg654qycxpv9m3wqj3vucsqxfwc5xnxp76axurwgulfzxm3jpd08ze320lz0d89ne8k92dymzcv8etr49eu72ha3qj7cpyztzmd4wg50qnrfpm94e38xvdz30ymckhz2lsjtwtunxpje5ad5dy9qgvx6vr99z7r3pdatgukjf03uy7kxfkvk0lqz0dntd896pt3eku0njqxshct9dcaqketdzpln74druvnlqs628vz5np8p3y0ue3xdlajj7xryrxztttgz9n6p7ryum0nueyss04dv679szj77k489ueln8c2tn3tq2e2h6z97m828lakrdcprr32fagw3x45mkvvzp3ue84hzr4z5u6ayweqywcpwkata2qmtcvne
    lastmodified: "2026-08-20T20:10:17Z"
    mac: ENC[AES256_GCM,data:TE2bJfCx9Lzuwh+N4RoWu+qU5j4sv2uo1Uv3XA6szGgjvjrdsiPNVUxhJRLfwlLaZzhTJZxaSWHg2feWOPdVy3Mkh9xOSjkKTfcFdvLLXRz/Pd4OYxb/BeGDuRx+DBieMZdRKR+4eWB+kPt79qNvaSBVqbEgtx/n/zkfEOw5qA8=,iv:t5W6B8HiDDj4ScUp11bvSt3lIFDurdiSxSaY+FGbEIE=,tag:s5pHgAwMy23R3raQIv1ljg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
