---
# Install with: ansible-galaxy collection install -r requirements.yaml
collections:
  # provides community.general.modprobe
  - name: community.general
    version: ">=12.6.0"

  # provides SOPS vars plugin for encrypted host_vars
  - name: community.sops
    version: ">=2.3.0"
