apiVersion: ENC[AES256_GCM,data:6Rk=,iv:ECCyFoHY4nHxeIZ/wzYC9abkl/Bj2kDNR40kBw8YZtc=,tag:SKEpgHDtb8c626dA6OBKUw==,type:str]
kind: ENC[AES256_GCM,data:uVIHJCw8,iv:mgQbHCCxwcPqhfjhKBuyWUoHkjDSGHKLmT3atN+I1H4=,tag:h5qIplSa2fQs5gdH282vLg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qRTt++DPPEEWpUMYhLaZMj8=,iv:frgh3VuxzQEYo2cHVS12EJfFQ21PZWqQNUV1psGsZyo=,tag:KbD9xAPVfz+5c+/dj/28PA==,type:str]
    namespace: ENC[AES256_GCM,data:NDuCGvjulxYD,iv:xaf2OUG7COygVcjTHS6mbKhmn0lfLET9Xm0seCwwZgs=,tag:Lv7BwObp7wAtI+o+siaIKQ==,type:str]
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:TMM=,iv:bvEY72BxcdoSkg6IoTkfJVX0G8KWK4mmhMgvH2c4TAg=,tag:jo5GFuJ63Q1543wEY5vTgA==,type:str]
type: ENC[AES256_GCM,data:uJxhlHrzem6xh0+HuLog5wxeT1/tcTYe,iv:nGpJ6hrYE9Z2xrRGsblBZpYDgLiL5Udz0BeBaTjv4yo=,tag:OT3x4TmsG0/GwVsSHB4faQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:5N1YPZt7UzsH,iv:GmHTeAuwUXu6SOOy2FzYoYVuD16s/thw1vlcc3+3I5I=,tag:Pr3I9Fz6H/Lg7yYMq285dQ==,type:str]
    password: ENC[AES256_GCM,data:eOD858oz65KoFKps8nrgmWwhzst0j1QFcQ==,iv:JjA3DZW0sBabGoSSE14DQk52M4Oep6eCjUx5gaBh5O4=,tag:BqXGjt0uRycI8Dg/nMNKTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5ICs2MzdtMCs2
            M0ltWUJ0dzJBaS9qNzBiRU5TdXhGL092Wk1GQ1Bucm5IQ2U5aTFZZzB5RUdlQ3Nm
            S2szNVUyaWhrb010V0E0U3F1MkYrNUlPZlFHQVhKcmthVGZwRVA3cjRqSThUNndQ
            UmhkZlp0WGhBb2syYThUZjBsNVlRb2hrR3JNa3VqeU9EWi83RE14dFJGT1V1ZEgy
            N3VHVFlEbHEwWlpLZmtncGtwRVBVdUw3R2lTNDJubElqZTRIRitvdk1XLzgyRDFt
            ZW9tWXpLNU9JcE8xU1ZxSWFqckxXL2VLbSt0OCtUL3RpQmh3Z3h3OGUwVUhEbDQv
            M0h2d1ZmSkdXa215YTV4YlNzSE5NZG1iK1ZMYmtwdHA2L2JrVnlUWVFzWWppVk9Y
            b3hvTmVXdXViZUxhbFFTbmUrNFlaVUZFQVlZMEw3b3BvV2dEWGpDZ21NeTc0c05w
            bXcvcndsOUg4OWtrT1dnc0Nld1JIdVYrUWIwcGZHRTllK3MzQUI0d2FCRlJydDZH
            cnpqcXFsRDFTU2hvcXg0ZWg3QVlWR3ppcDJIckx4RExvYldGbGlRVVdGQ0d2dkxi
            YjlWRmk4bHZ6OWlvd1VyeUU5YW5XeWlJS2o4YjhPbG5RY2E4WnErYzFUUVFabTBE
            WXFuTTh5UDd1WmpUZjArUStTdUsyVlg4a0JodjBXQVo0YTdyNmt1VCtLcS96czBL
            MVhmcXhudlZLUjJZcGJJRVBNdVRudmRiVTN5YldLR2l5MXFFM090Sk14RGNHYzE3
            TFIzZjgwWWRaWEZ4aUxsZWEwRlpTNDJRSksxV1NhdHZtZTA3M1dJM0RBa3M2REEx
            dGJCRXVVaitZaDJ2T2ZXYzZzZEVUWHVaYzVudjNFeDkvOTFzWEFjUG9tZVFiZzJm
            L2dvU05INEtpVkVKZXptU3hobVYrUXdSTUNhMnYxcXJ5NmcrKzZ4RkwwUGQxR0Zq
            bW9oN09pRmVWNDRYNENRV1Y3S3ZCQ3VBMEtxNjYvUHZoQXRpTjczUTcrUGMzMjhQ
            NEs3Q1NOcEhxZDRPcTJWem43MGVqYm5Ub21zMVFiTTFiMUpOa2dyY0c0a0xWSmFO
            TlpPU0hhK2JSdjc0eHltd0xwTnppYzYwOG9ucTFUbjNEeCtyc1R5ZC9xNGR4SGdV
            VS80a2JQYnFtc1V4TVFNR3ZBdFlZZjBnVDE0ZHhCUDU3VkUvOUh2cFhrdCtFcUd6
            RGpyOS85UmhMVms5RGxocGtORWVicmFibUJibExNbVduNWdIYlpqdkpOQk1paWlo
            MmZlckgwVy80RENZU3ZSTWxXdkJlMWtOZXlBdW1xNzRpTlVDaXFkanZ1L2pPdHBE
            djlFa3hsNXplR3c1TWpLTkhiSjViVmczM3VZbHkzTTFZUUwvc09NbjVRbmFSU3hQ
            dmpwSjlDa2dNdGJJaFFabUlTUnFxM1pqQWk0RmoreXZScThJTjNPSjNpR1lYdWdz
            NjFwemJvZ1drT1B4Zy9Jdkt5V0pRbERIZzB5S1NGb0ZiNHVtTjJaeExQc1d6a2Fk
            UkY0Ym9ldWswZDJpajlUbW5XNHpzNDBvZFlhaWlrc3paNDN5SFJKcmQ5bytJZzlx
            SzlKZzNZWWxBeG85RXhNV1FSR1hEQ0p3OE9UN0JCcGE1VjE3UVZ2dmVmL3NHWjhO
            OFJzK0dsanIzeXFDNjVzTGUrTTdYNkVSNFI4M0JGWVg3R1ZCYUpxaVluYURDWXRp
            Q3MxZ2hsaHJhc25hSVAvZFZjL2JyRVhoZzJnUjBGdzc1dDhiWXRsQ2Vjd1VhS3Za
            ZGUwNFJFcW04VldHUDAxRVNQRVRYOVQxdDBtbDRzUmVkT21tbXU1WU5kL3JpRFQz
            aGc3d0F3czJnSjFNcUQrWGg4cjRvRHZHVWptVVRpVnJSMnlFc2RCV1JzeEVrbE5P
            OUF1MEZ6RDBBVGNrdEE5bk1qWUthOHZ3MFR2ZS85QUN2Wnk3enh1eVFZNk1jQQpy
            cmF1WXpKRDkzNENwWVVUWU1jRDYvbWE0bUs4ZEZQZHl3SDJLSUwwRFQ4Ci0tLSBG
            L0lZYmZDVTZGMnR1aXBxbTdYZjg0K0ZzQlNhVjNaeW5aTVg0RC9wY0dFCvPUDuY0
            9MhrGZ5yEVZL6qdBDnQ6LKBWNJyYqiCJlamCyMrGRLCqM+r80hJ3/eZF1O36W9vu
            xvQ6vIGUrc+gjFk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1usjm3292p45jwd3277uwdksaacqnqd3e234nyev5f9twm77yr0fz6y5pxcyjfgqnt9aw8qereky8mkev59nanps7727u2djxa5avznjsrwar4qq724vcysf6q9gx5surc66qwdytz9ww4a284eayk2sgx5ka50d3sz357uxfx5x26nu4x5s9nffwuyp6qpet7du6up62wuydgdrd5cjasu2v39rka2uywrat0t7gs9t359j0x9u2ljpunlvggrfcz2y8vu3wkkju7nqyfy5qswukvd8njjsmnwt2qra9qjscwmfh5gf3549h7n5r506pncwt3zkn29wrcp7rdvzyu95uw68yqht9xj4hs9470uqvs3hs4lq6n0rdy5a8teyu369n03hfeas9tnxxzjvzpceec6w95uyr37ktrxrr4wflpgrxw3uj73y4w89pkfnurry0jwj29wnt9tj42lzzskpj2kpy7qfdgu44xkayeajme3n002q2av3zs49fl2rgdalzhtyy2e4jhpvlgw2rnpmuxfl59yvux99987vhaewtus7sgnnw3x396pc0py5vgen3rk7hwefgcrt9qeh5hznrtmcrz83ghehp3yws3z0r4jaj2yesmzjkejxh2qjeu5ngtepv7c6qqc6r8z8zxtenmgv04dmkcxj2n9hm5wep8nxtpyhzk4ttvrcqt6lrz0pwqvuvxeey57p2c44tjweetjvve98ek2x9d992sfth4xmrs9jr9pdmq72u37ew3cmq808v98f8z03tvny25sq2nms49a654gu754tl4sh45hrc5wfxy56m872mfqldr998cd3xrkec0tm6n05pdp60r9qg4d26gefg9e0vy824v0ua8x6cmcnfvpwpz444wzh8tq0dzlz3svx8a5ergt7n9dvr9fnqs4066pjzkt3y6psh5pc8v696wq7h77vmy0jt2mwq2z5rghw2r2fzgsfxq35hgy4svzn4tg0mhqsljxz05z3hh8mcg5wdquf7m2m4dnru82jgy4yq0kazjdnargxey8ylz3tc6dyrs7lyjwkqnpnyexay24w9q7feeq429yt9edqdak4yraen7hhvjntak5d6aw0ycvpgmuexruwhpp8vn0s4ndupdjq0auxrmraxt5xr2elrddzx9ajltz3zcl0eqvjxq3zx2sqt6f3mwsq42k343f42km6c79q46dqtqytgllms0ndyjuc0cxf2x3uxvyqp90t3kkt89dxcgw7de3axne4m28mj22clhd084v7xslypgy39xur295zk0frj0q290gakpt2p6sjfthe3frufw7jsed7zrvfvhlmqrxqxwnr349dlegvfr8qg5j8gs2ah2p4r5j0fr9qflfunf76v068mnpzw2kcnlzx09gaszn8mexzfgypfcqm9pa7rdqvem0c2zwnxwzq7lq225cscyfg8w75rgv8j3pj3zfrusv2wm9nqjp5z2wy0fvc752qhkhzlg0r665hmz03wfzh5ycwyuw7q223hup7v5xqg5v9mjmxx9p54uxdm9s7ukpdpvce4wevynjtu5yry8tj2f4qftwjuy5q5m4n2edgyehlqqgpw404h4fqg3xqu8djfhr3meveuyqt542muu5ra24resh82wxvy2vpa2uu27z5669djurggzyeagkgcy229jf35prex33rjk3nxrnp2lwzl5mrs9ewz58e83yyuk5v4v58q2u4ckhf8985vg6262drzmfvj923kp92mu2a9rhwj9vwwvyy8muaa0g2jx4r8qx5uff0k2kp22erug5tjvuhsckpzr3cafzdhsn56rekku42xvgvhr5pwxqkwkc3nja4hl2gxv475g8vjza2xm0u40l0zhc4l3w0hlkt5s8gcl88fhue6f43j2sezelexzwve75gyp5u7n0n5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGs0alVuRmMv
            MU8xOE93UGoxYUp1RnNaN3hFWDRSMloyOEtEQ2lKMFEzNzBpRDBkSkFVUEYvYmpQ
            dVlCTkxDYWRiNDNoZFo2SlMyUDNEbUhrc3g0cE9sSFBCTS8xeDEwWXR4bkxJYnJR
            SHJuSHZTcEJ4SVZObE1Jd3NMUzBnY0JYaVZSaWF4VGJzYmY3QWdaY1ZEbU5GQUZ4
            TGZBZ1Y4Kzc1M3dtUW0vMjB3T3lDMkYzRFgweXYzUXZoTHoxRzEvbUxkTnFrM0dL
            bzB0V3BhdkZGeTFNVC9MY2VXQjBBSUJvVkgrV1lwR2dvcjZNUlYzbWFRTnNKamhK
            dk93YWErVERIRWZVYnVGVEhxOGIxYnlhN2w1MzNDRXlLQlplcnhmVkZhbmdqSlpZ
            b092dHoySzhVa2MxcElwcHVDSENac29SRHEyN1luUDZlTTRCUW1tSXF0VWtRTFpU
            SmtjYVNza2tXQllsQUpsM2lwSEx2VmkyZFpFTjRWMWFlWjdWNXBCVFozU05pbUFD
            TXpmS3RYYStWQlo0ZzM1clB6VUEvaTk2cU96dnBNeUpIUUN5TkpkSEozOGRHVmVz
            cG81T0srd0FxQkJQT3NodEl3ZUhGT1hoYm9DRG1YK2c2ZE9iaGRJbXIwTEhXZnlm
            ZW5nRXVvNlNnL2FWZ0JVdWRJMXdkQVgvM2E0d2ZPK1QxZUV0aFB6QU8zaVdINnQ2
            QkFPck5jYzdhejdBdHM2cFo1bXBaT1hqM3pNRGhQNVZFYk0wdksyVVhyRUxydmY0
            OGd4YUIycm9VUVBnOWtGRDBGQy9yYWM1UkIxWVNOcEg0UXJBT09BWkhGblBnODlD
            RUgxZUZtd0xXS3FMQUJaL3o1QmNTVnlLdzdNTjR4Z2ZZNkJOa3YzdVlIRzc5RXdt
            bk5pem1lazhDanVnRnNJdG8rKzhsRWpBemFXbDBIVlhxKzJRK3pJTStVSm9VV3Vr
            M0NiNzNxS3JZTFBqdGI2bG9CeXBtTkRwaWZsU25ZNWhudVY0TnJuRnpYdVJvalh5
            cTNseW5pRFFvRmJTRXY3V3BBd2s1cno1RTBpWWczeUxWdTdxb0lsaFJjVmgzdVRX
            QzNxOXRwRkd1ZWdiUGpOUXRKcTAyR3BPRkdJdCtTTW8xRTVHM285U25LYUY4OS9W
            a1RPN0ZVV0toaTZZOCtMY3pOd2JPOW9qMXN1N2FNOExEL3dCRFltOUFNR1ZYVVc4
            Wm9jb2dsc25kUW9naURDbzg2MEZ3MHJNYXFNVHJyWHdOaXNOZ24yYTBVTElyWjlm
            djdWUmNZODE2c2xFSVFrNFo2U0pNczM1ZUlCaTBQRlJNeFE3TVlHZEc1NDNrUi9x
            NFI1cldsc0M0U0dheGRYOU5HM2hvck9ZRW9QRzRLOFdNR2d3MDdQYi9vV3E0bS9n
            T280UFdXMW9TbzE1TWdHRXluN3loZVZ3SHVIS1ozOFEvb2htUUxHRWZZdFJTQldT
            aVlCbmM0WkFibjBoQ3YvekxHQVJSeDZSZ3ovZXd6OFFFQkNpMjRPelB4a0ZKQWJE
            aWpvVzEyL3F1MDd3aUdiVUNSMDRGM25IQzA3WnlFOEQ1RXAvWU9ZWjNuVWxPUTVs
            STI1Z0lTYUpZUnloVm5YMDBwWU9oQzhvYUh6bTRIOTc2ZjRyZ1pkamFCV1FCcSt4
            SDhNQmhDV3NhZWVWcndNY2ZWaEJ4b2pQdlJreWNEeHZMRndyMEhxWjM0eVdBQTc1
            MDFYUjhoMmRlaGg2cHdQTEJheHIvVlpCclhmdmdLR0hZN0JRQmYvaFd1bU5KdjhC
            WERPRnJHSlZkaFR6bGRrNlJVbDhYTng0VUR1cFVRNnZCa1owTS9PbDNFSVdaSWJM
            MXkwQzl4ZkFlMGw3UDJUWE0vZ3pqUXFlemJKOHJCTlp4WldHOUJxZUtJcm1WcFM1
            QXBNemdoTU9SbUpiVGhTUXNkT1hqTjFic29EOUk5eGtNUGlPMytqaHRjTjlIZwpC
            WkU1cUFDTjBrQ0dVZXgwUTlEUWM2S25yR2dlTU9SeHdWQzhkWjBnT1drCi0tLSBj
            RjMzWVd4bzZFbnVrYXZyY2hxNGVkT1VOdUZhNFgyUEoySUxqMEFLamNNCsZhbwdr
            +d6q5YxyPq/SYyiX+ZZzqmzUR2T2l9K5BEu7ef8OLMNe8Lx7lKUGAEIXSqTIkmDR
            nRusee+/hP+JfR4=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1l0f68fyczayfen9sq4rqlag5rxkfwm55246zkeh5fqf5mdphz4ec8e8ftjrk4fm2usx3lctlaryp7nuer00gg7ezrxcvduje28q5jw0q0r80qs6xd9cqwvc4u5g99xgekzuvy5vry8qqq9x9x67vktr6tkwpglsy76pt53d0skd8vge94cytxzvnc5w795mzq0pqza8yw2xrpw4qxvu3h4g0wfe5w6whqhtgkdn7kv0y29krrjch9w88k66pkp83rsarawegr73sgm78j6wughuzegvp37cdjueushv3q6nfjgj0zpd80ek97059f89x0ny9zvlaqspvlkkft03ktnc5ejr2kxc8v8x9adyk7lyzzfh4c5v2gfkqq97zveewf64cy09p9sdmq7d9uaa4p6w9rn2ezfqpj52mvqq4f3pq33vrsdnft5afkvu28smdqx9scs4kae9ur80shxruvzzvg6prmkgjqgqua56zkf8p0pupegw5sxg6x7gjju5kw5duh3d7dgsdk6adjadhux36z3tk2nwmu50hme9f69f67zcr89h7gj7urfuqd9r9dwn6nxef5vc5japfe3mcyey4e0u4vw9rxgz8qyca8vjr9fdr9n26e7mjt4ujfv7nc0pyxyuh5aymtn662d7cj6a8xmznzvk894m8uuky507ag32dffhfze4evwdcxdxv3698sg26skxf76v9t4s2e255csun3fhtjg394n9twztmkayqhac4yd4cj9gv7fvw23te4qfte8a8g9ttryezn4yr69xp2ypjdw3ajvdkf2rlthqup6c957hn2rsag4uk5tqvdgps0c35l8hrn2z6gmzahy0e0jerq63j7uryh9wus7keywledu5w9pt4wmlheryew2hzl289prz8hmeph6ykeethwewpmvrfkyzxh9wy4hefxyu6vw0gs8zuknyswdpcry8tfh4ldzh0cwhac6qveajk0sspqhn4qxj9c67hzjaffr9cyta25qgqw92hxeq3rktlhnj5zyvtyu8e2qxp245plnzrnva8fjt4w98gkrqpqdfvp4qznqa8lhdxd46q2kdugv5wfds7p5zfaljer2xmgynp0p0el3zpafu69s2xghdtz9gx8pm6dkj8vvtrvm53x6sjqtxf27nalffcu2asve8sxmamc2r93p5qqkfdmznkxgtvyalxxc947az0gufytusna4dx3du3xq86aqpk756tvhneyspnqs6tvh523jslg5a3ffckvkf3ts2fcxzgjusjq4mv4a2zz0cxz37j2smvgs9capa3xm4j8pqnpatcnygjtfjptr9fuc4gdr9cqhsd3vq4apymnfz6enqvkhq3rgt2f2yyw9hrfjeqqmfhuv8tp6d8cgnh78pm947q9jpjagesh986ckm9x94dvq2zua3rjcst8yf992tsqashksmwtdaep0uek36hq8d2h3wyg5a87mfsx4zcxt67sla0jk95l3aut952daf3868tcj9r2f4jxd67x4fsc5t9gsdqe9dkpjctd2vz06fru6u58x9uvg654qycxpv9m3wqj3vucsqxfwc5xnxp76axurwgulfzxm3jpd08ze320lz0d89ne8k92dymzcv8etr49eu72ha3qj7cpyztzmd4wg50qnrfpm94e38xvdz30ymckhz2lsjtwtunxpje5ad5dy9qgvx6vr99z7r3pdatgukjf03uy7kxfkvk0lqz0dntd896pt3eku0njqxshct9dcaqketdzpln74druvnlqs628vz5np8p3y0ue3xdlajj7xryrxztttgz9n6p7ryum0nueyss04dv679szj77k489ueln8c2tn3tq2e2h6z97m828lakrdcprr32fagw3x45mkvvzp3ue84hzr4z5u6ayweqywcpwkata2qmtcvne
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGpQU1ExU2xF
            aTF2VUM3Y1pBNGREcmNZaTdjbGs3LzFkQWd1UWI4eE1JUlUrT1BnbS9hb1V3Vzgv
            L1dsVjgvaWIxWXZYL3RoVWY1aHR6QkY3SzlTYTE2QkI4WERTQ3gxYWQvOFRYRUVr
            MmRldWFoQUhtd3RKNnpWN3dCc0ZJSDRERThiY0ltRTNaU3NtYnJRZWN1SXF6Yit2
            N0JhRTkrL2VFSUtVMi9oNXhSWEdybEtTK0xHQUJleWVYUm1ES2I1TnhyVHZqVDNp
            NTdMR2tBYXBPS29rZjgzeDlGRU8wc0ttK2NsTDFna3M2akwrUDBkVDFlQVlkTCsw
            clB2cnIwWXBLNm9oeHozckVlZGtURXljSGRrNWFycWFNQUZRLy95a2FLZ2cxN3Bt
            YVk0bW50NHFXQWdxV1RQUFdnSlFWanVIVVhuemNSaE9OdDdlbGRwOXlSNk1ibHRW
            VUhERnRkbUhDZ2FRZTZadnRnRXpnWHBsMmNzSFFpb0w5aHA1RlUrdFhoV0lzOWk1
            N29KUnZRQVR4WHpMUkZhZFFqSFp0amhIY0tGcHdwZUVOR3V2OCthMFJCSGREOU1n
            V3NhbkFwc1haMHB3OWRIdTZUM2k5M09vSFA5QmZMcXh3NDFVSnFDZTkvUkpQZnEr
            Z0VmczBDTnNhTWpteFRRcGd6Si9BeHdld3JpVjhQamY1bEtEQVZTVi90dFpVZ24v
            VThtYTZVb3FqT25vV3NLQVpFbXRkTndCVlgxVVdKVVdicnRoYkNCYUdnYWZtbzBy
            SXB3Z1BtV0QvTDZrTmhaK1F1QytXR3NYcXc5UlIxdjByUCs0TS9aTWtLQUNwR3lr
            enJFUkpuaFQxSzFWOTB4NiswMHlpVWg5VjE2cUxZbWU1MXl6LzJiM0V0SC80NGQx
            WjlsZHdRWGpyb2VGYVdNN1JzL1RJMXQrSlE1LzBNbUlBWnRxNmU5dGkzOXJicXUx
            SHZCdWlzS0tGQ0o3dHlhWHlXeFduaVJmNU5Gd1Y5RS9vL1BHdXA2OWk3enJ6bnhU
            STJCTitJaldiL3F5SkNSaDdPMmJUOW1WbDBxMDkzZzJaUVJKTHB0S3FkdkQwWTlY
            OTBZdWhIamtrUEtNRXFpLzRlc3ZhOUxLZW5yZ0JIY0pZV2thaCtVa2ZBcGlOMkRh
            c0lCclIzOTRMRU1UbXRJanR2R3BzZXpwbnMvRWRHTzN2U1QrbTloM2Z0ZEpzbGl4
            eVROOVNmMTlPNXFNSGxlRHVWWXByNHh6eHJpN3BxZDIwU0tjczl2VG1ybUdNVjZK
            MjF1VW1UYTFCVnpwemFGaHFFUEhKcFVPZDh3YVpONitCZ1V5cS9pb2RSanFqS0xV
            d3djRkN1Z3N0SHJrWDgwTTY5VEU5d084N2lvbUZISjJjaWUyZHUrVzVJZ1hFenJQ
            dUN3eThxR2U5S1pNcmpJN3pUL0hoRGhJa0N6dngyNElrQkNMdXRPQ0VibTB2Y1Nl
            dk1zYmlJUEhrYVBhVDdkODJwQjhZRjRVVWFhTzlFMVJlY2MzeHd4ZmZpRTJLK1Y4
            MEVERHlSZnBlMHJ0dHZzaVdIczBiSTg2M2duc3NmYVhnVmtjV3JDNWNYM0x6c1Jn
            bkNBT3R0Tkpaa0wrN2pWMEVXdDRHQkRoRWRkMTNzaDJ3T2doTktCTXRKUHZjMWJ2
            UlVnWWwxV3ZRblF0QjcvN2dFOStSUVhiRVhHUGp6dHRQWDlkdzhWSFNCRlNPcm53
            TW1nV2NGYlZzdWV1NVBseG1QWm5TRzFhTUxSNTdYOER4TmFNcWhrUWlPbFhxS3pX
            blJjYzFTM2F5S1ZxSXhkdG1xZkZJVVdYdUt1eFZhR0JGd29MRkRTMXhwM3pZTk44
            RmF3M2xuNWVVWUFFSWRFV1Q5UWJCRFJQUE1NSFZ0SEErOC92OHdPQmhQN241N2JO
            SkVZZzFKUVlIeTZ5SFFoWnh5UHlNb21KdkZDWXkzb3N1ak1PSC9WdHhGN2NlZwpw
            ZEJ2aFlmYlJ0SzRGbGpwcGRZY2w1aFN0cGRkbWExdVZtUzJ4a0UxRCtRCi0tLSBw
            ZDdwNXZQSVlndCtob3U2SmZMMWNMYXRBWTc0cm1leENvdmw2ZkdnM3FJCm7OGyZi
            J7vqykYgg4mWZlaFMAapvCmEmy+H2GxbyMKzsLYo/vgR9yLR+WyK456agA4IPFtV
            OHexjARG8M9ej2w=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1fvw2zs3m8fucwpkkmwzc5fanjqk926xvzfmsvtrgvry0vz7szlzf98sugh6257m82y6tdjtr0t6kgda8802ftyu86g27rk47k4ajhv6tjalg9pse6am9pj7wlg7g6k53hwu5vm33gxgvaq7qz0gt0k64w4jpnvgcezek9ensguwr47xezh5zw3vpvcq3as7fjfx2d4tyhuc75qua3xw7h9sxf3j5rvlp9l5w5f79as975xwwfpwxckmhgnzzrvnupgy34kxra8gz9lpphc243x59u8rjep9fwewg5eu59uh6ymaz64lflvyjgrcc2u2zwqzx43smf2cvp0zx86wgcjqnpw4wtqcf525edp7t6v6savwywsj7hwvccy2mxyt8makfd3644jv20vdg5cuya3r05h5myhv2npxlxxsa8x4mj2jl5tdernzst7pfg8xxc3ra5qvje7j84t7r2cz949tenq3jpwuww7uudvzqxv654q2vpvzg7nqx435c0dx69sywc99ldqlukf3dsh4n9v6tkt9tqcrcrz53ckpmdqy37ljcdruky9wlzprahz3hc36ffvk24huetf7ucygn84dw80a5vvdtt007sq8nfq5xcwgpdejr9wmn4sx95uh6fy26vqvsxj4q09hqhd523fnm8yd8n7ve35peuqj5denhddtat9xddx3yzunnmcugct23qx35s3llrrqcf2zyyl8zw79pcl60fdxyhvda7tysymrzycqyx7w3lxj8z2f8uht90mezfd9p4zfh4p695f720z2q0mahh8w6zx4asfhag3r0e6j5fh4pq8t4vvsxdxjer2ynd9rp7lqkf7h50qs5cpvsj9x2659cc03mzd3yxu88fwhwm546jnfq72jskrldqdfslxfa4t9y0utrmk430sa0fxef7yr47e5q7p4re3cxqsl7pfnml3cxg9574mc68phj2gfn4r4w8z0uqdkfeq9n94axdk5fgpsjy7nzqs443r2hxfl80mcns9t75tpyxnydpe7qe38pr0yuwpvmwknlj55mjtu59vvnjjazsngy0vp9ze7wt4e9pcwf88uhgjzt3fuzwvgkr6t3g3924nt22yt66q7ysp9q9k9fnaevnqf7pfu9jccjkmqd2kk27e3u2j93efh3x9jhkkzazx3jqsyyfxg8ga4k0dvyyw2q7ym3jm8pruwpswn3wpyeadszmqms86sgwc25jf30w9mmr8qv855zrrezcqzdqypm62xc3cmmjsqjkrsz5t2jef2lw9yx6ppyvjxvpdfzexgdk6gnj8z73ty976j5ualgwt7w8vktvc87mmypdtup6r54d2q98xga5p9v2zmucrr3s9259fy92pmn7qvv0afcx9sys2vye8zhdzkvxaq56zncp63rkm3kglsv2n5h8f3pg7g3prpg6k36j4knq0ygxz7ngj3wlvd3ygnyqg2tnn6fmzvs4628fedq3fscqn98dqq89p9ksxsp2lcfdmg6nl6q2apvagket9tfprzqh5cnv596xnjez9a2zyevw6n9shdsj8rqypstxwznreexxp93rgljtmjagyncp9c6x4ul8dcuvryqgqk09jg8ed0mnx59k7u26k5cck4vchdd8vryk4pl92sp8rlenaxfcfdgu9cvz5u2q4yxkq05t7x6vsdlwdwt6dvwdqygprkfzrlu3dd8q3m49s4dx97q00un8x9ztw6sfrxukcz0hdn57w3nq27kx60jd09pyyfg6jc2q84cwegkdgqkuwdk5s4t2wqtsqgcfcvjetzm2pzsex2dfz2t9frxf25f2pt4c92nl6zhwqqg248f0nxdcae92klxral0503zqqf0p686n9k7m7lq4c23pvmw34xx23rjn6dg5ghx32pw3lmq6vn9em4czxvdnm53deajt5hqx2c8
    lastmodified: "2026-09-22T17:50:57Z"
    mac: ENC[AES256_GCM,data:Fr8xVZvTii4fMKZKwDUDj/f6z4hmP1tWMVCrnJHbElyH6RuymvUYTSHysHGqoroP12+F+bsd+F3agn9Cag42AHNG/hSmppOXfEnmZr4MYvnI3QzfO3rQ8srqs+DW2F6beexELfXs9YqGtjETgZ4vXJHDJvjaErFTWbK3lLJZ1+A=,iv:7dASjuWMnECOJegf3Z6+aZlfX+01ilEz4jmvPkFJNSo=,tag:wbje8iYMWfa+NWa1LgXeTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
